Teo develop
Systemorph/IFRS17CalculationEngine pull request #100
Opened 2022-11-23 09:19 UTC by tkukuljan

#64

2022-11-24 14:48 UTC, tkukuljan commented
The pull request is finished by Andrea and me.

FYI: @dcolleoni @dtrzesniak @amuolo

2022-11-25 07:56 UTC, dcolleoni requested changes
You are reverting many changes that were done in previous PR. 
You have most probably resolved conflicts in the wrong way. 
Thanks for fixing this.

2022-11-25 07:56 UTC, dcolleoni commented on ifrs17/Import/Importers.ipynb
> +                "The [Analysis of Change configuration](../DataModel/DataStructure#aoc-step-configuration) is parsed from the input file and complemented with defaults to allow for an easy insertion
AoC Steps

2022-11-25 07:56 UTC, dcolleoni commented on ifrs17/Import/Importers.ipynb
> +                "\nThe following categories have been identified based on the *Order* of the novel Aoc step:",
revert

2022-11-25 07:56 UTC, dcolleoni commented on ifrs17/Import/Importers.ipynb
> +                "\nThe new Aoc Configurations are created with the same order of the Aoc Types. "
revert

2022-11-25 09:29 UTC, dcolleoni approved these changes

2022-11-25 09:38 UTC, merged